### ISSUE TITLE
Pagina de meus pedidos

### ISSUE THREAD

**Issue by EliasFernandes02** [Projeto-DripStore-FullStack/Dripstore#20]
![image](https://github.com/user-attachments/assets/6fae9670-fb0a-4a58-9b6e-cce113d95fe8)
Pagina de meus pedidos precisa-se trocar a fonte e quando selecionado a página, ficar marcado a cor rosa a esquerda.

**Comment by SamuelMagalhaes** [comment]
Alteraçõe feitas
